# Spring Data Source ?? - MySQL DB ?? ??

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoapp_db
    username: root
    password: tkdwls1!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#    database-platform: org.hibernate.spatial.dialect.mysql.MYSQL56InnoDBSpatialDialect